### PR TITLE
chore(deps): bump gatsby-transformer-remark-rehype to 4.0.0

### PR DESCRIPTION
**Pull request by diauweb**
Bump `gatsby-transformer-remark-rehype` to 4.0.0, supporting new gatsby.

- Temporarily disabled `remark-details` as it is incompatible.
- Because `remark-details` is disabled, pages render differ.

And please review changes regarding toc part

### CODE REVIEW

**Comment by Enter-tainer** [comment]
remark math应该也需要bump一下，新的remark math支持新的gastby和remark

**Comment by Enter-tainer** [comment]
现在就waiting remark-details 啦

**Comment by Enter-tainer** [comment]
> not my fault
> wait remark-details & rehype-details

为什么 remark-details 也要 wait🤔，我以为只需要 wait rehype details 的

**Comment by diauweb** [comment]
> 为什么 remark-details 也要 wait🤔，我以为只需要 wait rehype details 的

npm上没发版

**Comment by Enter-tainer** [comment]
details 工作了, 还有别的东西在 blocking 这个 pr 吗? 感觉是不是可以合了

**Pull request merged**
